#!/usr/bin/env bash
#
# Run tests for shell examples
#
# Copyright © 2025 Ernst Strüngmann Institute (ESI) for Neuroscience
# in Cooperation with Max Planck Society
#
# SPDX-License-Identifier: MIT
#

# Exit right away if a command returns non-zero status.
set -e

# Read parameters from setup file
thisFolder=`dirname "$(readlink -f "$0")"`
source "${thisFolder}/tests.setup"

# Get directory structure and set up tmp file to capture stdout
rootFolder=`dirname ${thisFolder}`
shellFolder="${rootFolder}/shell"
tmpout="${shellFolder}/tmp.txt"

# Clean up remains of potentially failed previous test runs
rm -f "${tmpout}"

# ----------------------------------------------------------------------
info "Testing load_params.sh...."
"${shellFolder}/load_params.sh" > "${tmpout}"

datename=$(date +"%Y-%m-%d")
debug "Testing correct write of header"
grep -qw "This is load_params.sh version" "${tmpout}"
if [ $? -ne 0 ]; then
    warn "Expected initial header write not found"
    fail=1
fi
debug "Testing correct write of first line"
grep -qw "${datename}.*We begin here" "${tmpout}"
if [ $? -ne 0 ]; then
    warn "Expected first 'print_input' write not found"
    fail=1
fi
debug "Testing correct write of second line"
grep -qw "${datename}.*first second third" "${tmpout}"
if [ $? -ne 0 ]; then
    warn "Expected second 'print_input' write not found"
    fail=1
fi
debug "Testing correct write of third line"
grep -qw "${datename}.*And end there" "${tmpout}"
if [ $? -ne 0 ]; then
    warn "Expected third 'print_input' write not found"
    fail=1
fi

# If any line has not been printed, the test failed
if [[ -n "${fail-}" ]]; then
    error "Running load_params.sh did not print expected output"
    exit 1
fi

passed "Executed load_params.sh successfully"

# ----------------------------------------------------------------------
info "Testing log_msg.sh...."
log="./tmp.log"
rm -f "${log}"

# Force zero return code to not fail test due to final error-call in log_msh.sh
"${shellFolder}/log_msg.sh" > "${tmpout}" || true

debug "Ensure that initial debug message was not printed"
grep -vqw "This message is not shown" "${tmpout}"
if [ $? -ne 0 ]; then
    warn "Debug message not hidden"
    fail=1
fi
grep -qw "${datename}.*=== An info message" "${tmpout}"
if [ $? -ne 0 ]; then
    warn "First INFO message not shown"
    fail=1
fi
grep -qw "${datename}.*WARNING: A warning message" "${tmpout}"
if [ $? -ne 0 ]; then
    warn "Initial warning message not shown"
    fail=1
fi
grep -qw ">>> A big announcement! <<<" "${tmpout}"
if [ $? -ne 0 ]; then
    warn "Announcement not shown"
    fail=1
fi
grep -qw "${datename}.*DEBUG: This message is shown" "${tmpout}"
if [ $? -ne 0 ]; then
    warn "Debug message not shown despite enabled 'debugflag'"
    fail=1
fi
grep -qw "${datename}.*=== This messages is printed and logged to ./tmp.log" "${tmpout}"
if [ $? -ne 0 ]; then
    warn "Second info message not shown"
    fail=1
fi
grep -qw "${datename}.*ERROR: Crash with an error" "${tmpout}"
if [ $? -ne 0 ]; then
    warn "Final error message not shown"
    fail=1
fi

grep -qf "${log}" "${tmpout}"
if [ $? -ne 0 ]; then
    warn "Log file not populated"
    fail=1
fi

# If any warning has been issued, the test failed
if [[ -n "${fail-}" ]]; then
    error "Running logging example did not produce expected output. "
    exit 1
fi

passed "Executed logging example successfully"

# Cleanup
debug "Cleaning up log file created by log_msg.sh"
rm -f "${log}"

# ----------------------------------------------------------------------
info "Testing queries_run.sh...."
debug "Sending 'y' and 'RETURN' key to script"
(echo "y"
 echo -ne "\n") | "${shellFolder}/queries_run.sh" > "${tmpout}" 2>&1

grep -qw "We're now asking a simple yes/no question..." "${tmpout}"
if [ $? -ne 0 ]; then
    warn "Initial prompt not shown"
    fail=1
fi
grep -qw "Obviously..." "${tmpout}"
if [ $? -ne 0 ]; then
    warn "First provided answer not accepted"
    fail=1
fi
grep -qw "Press RETURN/ENTER to continue or any other key to abort" "${tmpout}"
if [ $? -ne 0 ]; then
    warn "Second prompt not shown"
    fail=1
fi
grep -qw "This message is only displayed if the user pressed the RETURN key before" "${tmpout}"
if [ $? -ne 0 ]; then
    warn "Second provided answer not accepted"
    fail=1
fi

# If any warning has been issued, the test failed
if [[ -n "${fail-}" ]]; then
    error "User query test did not produce expected output. "
    exit 1
fi

passed "Executed user query example successfully"

# # ----------------------------------------------------------------------
# info "Testing pass_vars.sh...."
# dummyfile="./dummy.txt"
# rm -f "${dummyfile}"

# debug "Run script and ensure temp output file has been created"
# /usr/bin/env bash "${shellFolder}/pass_vars.sh" > "${tmpout}"
# if [ ! -f "${dummyfile}" ]; then
#     warn "Array processing example script did not create temporary file"
#     fail=1
# fi

# debug "Compare expected to actual output generated by script"
# grep -qf "${thisFolder}/pass_vars.ref" "${tmpout}"
# if [ $? -ne 0 ]; then
#     warn "Log file not populated"
#     fail=1
# fi

# # If any warning has been issued, the test failed
# if [[ -n "${fail-}" ]]; then
#     error "Running array processing script did not produce expected output. "
#     exit 1
# fi

# passed "Executed array processing script successfully"

# # Cleanup
# debug "Cleaning up tmp file created by pass_vars.sh"
# rm -f "${dummyfile}"

# ----------------------------------------------------------------------
info "Testing rsync_examples.sh...."
rsyncFolder="${shellFolder}/rsync"

/usr/bin/env bash "${rsyncFolder}/rsync_examples.sh" > /dev/null

debug "Ensure all expected files/directories have been created"
if [ ! -d "${rsyncFolder}/dir1" ]; then
    warn "Exemplary directory dir1 has not been created"
    fail=1
fi
if [ ! -d "${rsyncFolder}/dir2" ]; then
    warn "Exemplary directory dir2 has not been created"
    fail=1
fi
if [ ! -d "${rsyncFolder}/dir3" ]; then
    warn "Exemplary directory dir3 has not been created"
    fail=1
fi
if [ ! -d "${rsyncFolder}/dir1/sourcedir" ]; then
    warn "Exemplary directory dir1/sourcedir has not been created"
    fail=1
fi
if [ ! -f "${rsyncFolder}/filelist.txt" ]; then
    warn "File-listing filelist.txt has not been created"
    fail=1
fi

debug "Ensure sourcedir was populated with dummy files"
nfiles=`find "${rsyncFolder}/dir1/sourcedir/" -mindepth 1 -maxdepth 1 -type f -name "file*.txt" | wc -l`

if [[ "${nfiles}" -ne 20 ]]; then
    warn "Unexpected number of dummy files in 'sourcedir' - Expected: 20, Found: ${nfiles}"
    fail=1
fi

# If any warning has been issued, the test failed
if [[ -n "${fail-}" ]]; then
    error "Running rsync example script did not produce expected output. "
    exit 1
fi

passed "Executed rsync example script successfully"

# Cleanup
debug "Cleaning up tmp folders/files created by rsync_examples.sh"
rm -rf "${rsyncFolder}/dir1"
rm -rf "${rsyncFolder}/dir2"
rm -rf "${rsyncFolder}/dir3"
rm -f "${rsyncFolder}/filelist.txt"

# ----------------------------------------------------------------------
# Final cleanup
rm -f "${tmpout}"

exit 0
