#
# Copyright © 2025 Ernst Strüngmann Institute (ESI) for Neuroscience # in Cooperation with Max Planck Society
#
# SPDX-License-Identifier: CC0-1.0
#
channels:
- conda-forge
dependencies:
- python <3.14,>=3.8
- reuse
- sqlite
- pip
- pip:
  - sphinx_automodapi
name: esi-ntials
